# NumPy exercises

In [1]:
#import the Numpy package
import numpy as np

In [2]:
#Set the random seed
np.random.seed(859)

In [5]:
#Create a random array of 100 values between 0 and 1
arr_1 = np.random.rand(100)

#Display the resulting array
arr_1

array([0.19534306, 0.98725283, 0.32144554, 0.43665877, 0.52092128,
       0.99185892, 0.4512966 , 0.46528795, 0.42855089, 0.42164073,
       0.03478829, 0.41085605, 0.63824602, 0.79883719, 0.70045127,
       0.13252944, 0.96171051, 0.72157607, 0.1310275 , 0.43826953,
       0.39504279, 0.75529867, 0.79063578, 0.04852885, 0.5892303 ,
       0.86035591, 0.73844954, 0.50345922, 0.80521448, 0.92585221,
       0.87377377, 0.23575141, 0.88926495, 0.43608169, 0.69485928,
       0.59606518, 0.46230774, 0.04288529, 0.25379888, 0.15070365,
       0.94760425, 0.53791765, 0.62965182, 0.1463806 , 0.29600102,
       0.70063342, 0.3323304 , 0.56427427, 0.73583733, 0.5649425 ,
       0.05617873, 0.33023866, 0.07427347, 0.97744051, 0.1546918 ,
       0.86850714, 0.87487524, 0.0962033 , 0.13467626, 0.49267617,
       0.19393684, 0.316166  , 0.7439104 , 0.37770906, 0.69287993,
       0.63753284, 0.50990078, 0.219774  , 0.47966486, 0.32343292,
       0.48182611, 0.30777753, 0.41054541, 0.31251079, 0.38951

In [6]:
#Report the shape of the resulting array
arr_1.shape

(100,)

In [7]:
#Report the data type of the resulting array
arr_1.dtype

dtype('float64')

In [8]:
#Remote the mean value of all values in your array
arr_1.mean()

0.47853087686279094

In [10]:
#Multiply each value in your array to get values between 0 and 100, saving the results as "arr_2"
arr_2 = arr_1*100
arr_2

array([19.5343064 , 98.72528321, 32.14455398, 43.6658768 , 52.09212839,
       99.18589167, 45.12965977, 46.52879454, 42.85508869, 42.16407299,
        3.47882881, 41.08560519, 63.82460164, 79.88371851, 70.04512687,
       13.25294436, 96.1710514 , 72.1576071 , 13.10275018, 43.82695275,
       39.5042794 , 75.52986698, 79.06357832,  4.85288482, 58.92303   ,
       86.03559066, 73.84495441, 50.34592225, 80.5214485 , 92.58522122,
       87.3773769 , 23.57514085, 88.92649456, 43.60816857, 69.48592808,
       59.60651839, 46.23077364,  4.28852856, 25.37988768, 15.07036524,
       94.76042494, 53.791765  , 62.96518169, 14.63805969, 29.60010227,
       70.06334184, 33.23304018, 56.42742658, 73.58373259, 56.4942497 ,
        5.6178726 , 33.0238656 ,  7.42734651, 97.74405076, 15.46918034,
       86.85071356, 87.48752388,  9.62033032, 13.46762577, 49.26761706,
       19.39368434, 31.61659973, 74.39103998, 37.77090586, 69.28799317,
       63.75328384, 50.99007817, 21.97739997, 47.96648628, 32.34

In [20]:
#Reshape the array above to be 25 rows and 4 columns, saving the result as "arr_3"
arr_3 = arr_2.reshape(25,4)
arr_3

array([[19.5343064 , 98.72528321, 32.14455398, 43.6658768 ],
       [52.09212839, 99.18589167, 45.12965977, 46.52879454],
       [42.85508869, 42.16407299,  3.47882881, 41.08560519],
       [63.82460164, 79.88371851, 70.04512687, 13.25294436],
       [96.1710514 , 72.1576071 , 13.10275018, 43.82695275],
       [39.5042794 , 75.52986698, 79.06357832,  4.85288482],
       [58.92303   , 86.03559066, 73.84495441, 50.34592225],
       [80.5214485 , 92.58522122, 87.3773769 , 23.57514085],
       [88.92649456, 43.60816857, 69.48592808, 59.60651839],
       [46.23077364,  4.28852856, 25.37988768, 15.07036524],
       [94.76042494, 53.791765  , 62.96518169, 14.63805969],
       [29.60010227, 70.06334184, 33.23304018, 56.42742658],
       [73.58373259, 56.4942497 ,  5.6178726 , 33.0238656 ],
       [ 7.42734651, 97.74405076, 15.46918034, 86.85071356],
       [87.48752388,  9.62033032, 13.46762577, 49.26761706],
       [19.39368434, 31.61659973, 74.39103998, 37.77090586],
       [69.28799317, 63.

In [13]:
#Show the 3rd row of this array
arr_3[2,]

array([42.85508869, 42.16407299,  3.47882881, 41.08560519])

In [19]:
#Show the values in the 2nd column of this array
arr_3[0:25,1]

array([98.72528321, 99.18589167, 42.16407299, 79.88371851, 72.1576071 ,
       75.52986698, 86.03559066, 92.58522122, 43.60816857,  4.28852856,
       53.791765  , 70.06334184, 56.4942497 , 97.74405076,  9.62033032,
       31.61659973, 63.75328384, 32.34329242, 31.2510787 , 63.53468315,
       81.16156944, 16.57063226,  1.62980965, 44.60647772, 71.2464773 ])

In [21]:
#Show the mean of the values in the 2nd column
arr_3[0:25,1].mean()

56.783663651825506